before_script:
  - export COMPOSER_CACHE_DIR=/cache/composer
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - export typo3DatabaseHost="mysql"
  - export typo3DatabaseUsername="root"
  - export typo3DatabasePassword="root"
  - export typo3DatabaseName="templavoila"
  - rm composer.json
  - mv Tests/Build/composer.json .
  - php -v
  - composer -V
  - composer install --no-interaction --no-progress --prefer-dist

test:5.6:
  tags:
    - docker
    - php56-cli
  services:
    - mysql:5.6
  variables:
    MYSQL_ROOT_PASSWORD: root
  script:
    - find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
    - php .Build/bin/phpunit --coverage-text --colors --configuration .Build/Web/typo3conf/ext/templavoila/Tests/Build/UnitTests.xml
    - php .Build/bin/phpunit --coverage-text --colors --configuration .Build/Web/typo3conf/ext/templavoila/Tests/Build/FunctionalTests.xml

test:7.0:
  tags:
    - docker
    - php70-cli
  services:
    - mysql:5.6
  variables:
    MYSQL_ROOT_PASSWORD: root
  script:
    - find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
    - php .Build/bin/phpunit --coverage-text --colors --configuration .Build/Web/typo3conf/ext/templavoila/Tests/Build/UnitTests.xml
    - php .Build/bin/phpunit --coverage-text --colors --configuration .Build/Web/typo3conf/ext/templavoila/Tests/Build/FunctionalTests.xml
