language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

addons:
  apt:
    packages:
    - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - export COMPOSER_PROCESS_TIMEOUT=1800;
  - export TYPO3_PATH_WEB=$TRAVIS_BUILD_DIR/.Build/Web;
  - rm composer.json
  - mv Tests/Build/composer.json .
  - composer require typo3/cms=7.6.*

script:
  - >
    echo;
    echo "Running php lint";
    find . \( -path "./.Build" -o -path "./vendor" \) -prune -o -name \*.php -print | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running unit tests";
    php .Build/bin/phpunit --coverage-clover=unittests.clover --colors --configuration .Build/Web/typo3conf/ext/templavoila/Tests/Build/UnitTests.xml;
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    php .Build/bin/phpunit --coverage-clover=functionaltests.clover --colors --configuration .Build/Web/typo3conf/ext/templavoila/Tests/Build/FunctionalTests.xml;

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover unittests.clover;
  - php ocular.phar code-coverage:upload --format=php-clover functionaltests.clover;
